# Generated by Django 3.2.6 on 2021-08-05 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='track_album_cover',
            field=models.CharField(default=1234, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='track_artist',
            field=models.CharField(default=1234, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='track_audio',
            field=models.CharField(default=1234, max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='content',
            name='track_title',
            field=models.CharField(default=1234, max_length=500),
            preserve_default=False,
        ),
    ]
