# Generated by Django 3.2.6 on 2021-08-08 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='content',
            name='is_published',
            field=models.BooleanField(default=True),
        ),
    ]
