# Generated by Django 3.2.6 on 2021-08-08 07:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_content_is_published'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='content',
            name='is_published',
        ),
    ]
