# Generated by Django 3.2.6 on 2021-08-06 05:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_rename_track_title_content_track_title1'),
    ]

    operations = [
        migrations.RenameField(
            model_name='content',
            old_name='track_title1',
            new_name='track_title',
        ),
    ]
